# Generated by Django 6.0.8 on 2026-08-25 05:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="activityentry",
            name="external_id",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AddField(
            model_name="activityentry",
            name="source",
            field=models.CharField(
                choices=[("manual", "Manual"), ("strava", "Strava")],
                default="manual",
                max_length=10,
            ),
        ),
        migrations.AddConstraint(
            model_name="activityentry",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_id", ""), _negated=True),
                fields=("user", "external_id"),
                name="unique_external_activity_per_user",
            ),
        ),
    ]
