# Generated by Django 6.0.8 on 2026-08-25 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0002_activityentry_external_id_activityentry_source_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="weightentry",
            name="source",
            field=models.CharField(
                choices=[("manual", "Manual"), ("google_health", "Google Health")],
                default="manual",
                max_length=15,
            ),
        ),
    ]
