# Generated by Django 6.0.8 on 2026-08-24 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="goal",
            name="revision_note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="goal",
            name="revision_requested",
            field=models.BooleanField(default=False),
        ),
    ]
