# Generated by Django 6.0.8 on 2026-08-25 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0002_googlehealthaccount"),
    ]

    operations = [
        migrations.AddField(
            model_name="googlehealthaccount",
            name="needs_reauth",
            field=models.BooleanField(default=False),
        ),
    ]
